name: KEMI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - pip
  - pip:
      - sympy
      - numpy
      - matplotlib
      - pandas
      - beautifulsoup4
      - chempy
