name: KEMI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - sympy
      - numpy
      - matplotlib
      - pandas
      - beautifulsoup4
      - jupyter notebook -U
